-- MySQL Script generated by MySQL Workbench
-- Fri Jan 10 16:33:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NOT NULL,
  `function` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role_id` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `modification_date` DATETIME NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `role_id1` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id1`, `admin_id`),
  INDEX `fk_user_role_idx` (`role_id1` ASC) VISIBLE,
  INDEX `fk_user_admin1_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id1`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `birthdate` DATETIME NOT NULL,
  `street_number` VARCHAR(250) NOT NULL,
  `street_number` VARCHAR(250) NOT NULL,
  `phone_number` INT NOT NULL,
  `city_number` INT NOT NULL,
  `city_number` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cv_link` VARCHAR(255) NOT NULL,
  `lm_link` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_candidate_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `light_description` VARCHAR(100) NOT NULL,
  `complete_description` VARCHAR(250) NOT NULL,
  `siret_number` INT NOT NULL,
  `phone_number` INT NOT NULL,
  `street_number` INT NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `cedex_number` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_company_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`annonces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`annonces` (
  `idannonces` INT NOT NULL AUTO_INCREMENT,
  `creation_date` VARCHAR(45) NOT NULL,
  `modificaiton_date` VARCHAR(45) NOT NULL,
  `light_description` VARCHAR(45) NOT NULL,
  `complete_description` VARCHAR(45) NOT NULL,
  `remuneration` VARCHAR(45) NOT NULL,
  `experience` VARCHAR(45) NOT NULL,
  `work` VARCHAR(45) NOT NULL,
  `field` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  `is_apply` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idannonces`),
  INDEX `fk_annonces_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_annonces_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidate_applyance_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidate_applyance_list` (
  `candidate_id` INT NOT NULL,
  `annonces_id` INT NOT NULL,
  `is_apply_annonces` TINYINT NOT NULL,
  INDEX `fk_candidate_applyance_list_candidate1_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `fk_candidate_applyance_list_annonces1_idx` (`annonces_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidate_applyance_list_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `mydb`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidate_applyance_list_annonces1`
    FOREIGN KEY (`annonces_id`)
    REFERENCES `mydb`.`annonces` (`idannonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `light_description` VARCHAR(100) NOT NULL,
  `compl_description` VARCHAR(255) NOT NULL,
  `admin_id` INT NOT NULL,
  `picture` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`, `admin_id`),
  INDEX `fk_articles_admin1_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidate_favorite_annonce_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidate_favorite_annonce_list` (
  `candidate_id` INT NOT NULL,
  `annonces_id` INT NOT NULL,
  INDEX `fk_candidate_has_annonces_annonces1_idx` (`annonces_id` ASC) VISIBLE,
  INDEX `fk_candidate_has_annonces_candidate1_idx` (`candidate_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidate_has_annonces_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `mydb`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidate_has_annonces_annonces1`
    FOREIGN KEY (`annonces_id`)
    REFERENCES `mydb`.`annonces` (`idannonces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articles_favorite_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articles_favorite_list` (
  `articles_id` INT NOT NULL,
  `candidate_id` INT NOT NULL,
  INDEX `fk_articles_has_candidate_candidate1_idx` (`candidate_id` ASC) VISIBLE,
  INDEX `fk_articles_has_candidate_articles1_idx` (`articles_id` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_candidate_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `mydb`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_candidate_candidate1`
    FOREIGN KEY (`candidate_id`)
    REFERENCES `mydb`.`candidate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
